--ENUM TYPES
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'theme_type') THEN
        CREATE TYPE public.theme_type AS ENUM ('light', 'dark');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
        CREATE TYPE public.user_status AS ENUM ('admin', 'user');
    END IF;
END $$;

--TABLES
CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username character varying(100) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    email character varying(150),
    phone_number character varying(50) UNIQUE,
    role character varying(50),
    token character varying(255),
    theme public.theme_type DEFAULT 'light' NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    last_login timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS public.contains (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    img character varying(255),
    name character varying(150) NOT NULL,
    type character varying(100), 
    category character varying(100),
    description character varying(150),
    price numeric(10,2) NOT NULL,
    count integer DEFAULT 0,
    contains_id bigint,
    CONSTRAINT fk_product_contains FOREIGN KEY (contains_id) REFERENCES public.contains(id)
);

CREATE TABLE IF NOT EXISTS public.cart (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.cart_items (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer DEFAULT 1 NOT NULL CHECK (quantity > 0),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (cart_id, product_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES public.cart(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);

CREATE TABLE IF NOT EXISTS public.order_table (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint,
    cart_id bigint,
    address character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_order_cart FOREIGN KEY (cart_id) REFERENCES public.cart(id)
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.order_table(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.delivery_address (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    postcode integer,
    city character varying(100),
    road character varying(100),
    house_number character varying(20),
    CONSTRAINT fk_delivery_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.billing_details (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    postcode integer,
    city character varying(100),
    road character varying(100),
    house_number character varying(20),
    CONSTRAINT fk_billing_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

--INDEXES
CREATE INDEX IF NOT EXISTS idx_billing_user_id ON public.billing_details (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON public.cart_items (cart_id);
CREATE INDEX IF NOT EXISTS idx_delivery_user_id ON public.delivery_address (user_id);
CREATE INDEX IF NOT EXISTS idx_order_user_id ON public.order_table (user_id);
CREATE INDEX IF NOT EXISTS idx_products_contains_id ON public.products (contains_id);

--ALTER TABLE
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='gender') THEN
        ALTER TABLE public.users DROP COLUMN gender;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='rate') THEN
        ALTER TABLE public.products DROP COLUMN rate;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='stock_count') THEN
        ALTER TABLE public.products DROP COLUMN stock_count;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='type') THEN
        ALTER TABLE public.products ADD COLUMN type character varying(100);
    END IF;

    RAISE NOTICE 'run complete without errors';
END $$;